[tools]
bun = "1.3.4"
gh = "2.83.2"
ghcup = "latest"
lefthook = "latest"
neovim = "latest"
node = "lts"
pnpm = "10.25.0"
ripgrep = "15.1.0"
rust = "latest"
starship = "latest"
stylua = "latest"
uv = "0.9.17"

[settings]
experimental = false
