# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[nodejs]
disabled = true

[custom.git_user]
description = "git user.name"
require_repo = true
command = 'git config --local user.name || git config --global user.name || echo "❌Unset Git User"'
when = 'git config user.name >/dev/null 2>&1'
format = 'as [$output]($style) '
style = 'bold cyan'

