[tools]
bun = "1.3.4"
delta = "0.18.2"
fzf = "0.67.0"
gh = "2.83.2"
ghcup = "0.1.50.2"
ghq = "1.8.0"
jq = "1.8.1"
lefthook = "2.0.11"
neovim = "0.11.5"
node = "24.12.0"
pnpm = "10.25.0"
ripgrep = "15.1.0"
rust = "1.92.0"
starship = "1.24.1"
stylua = "2.3.1"
uv = "0.9.17"
zellij = "0.43.1"

[settings]
experimental = false
